[WIP] New DynamoDB interface
hack4impact-uiuc/globalgiving-depth pull request #29
Opened 2019-03-19 19:39 UTC by JoshBurke

Resolves issue #28 

This PR adds a new dynamo_db.py file in the utils/dataset_db folder. This is an interface for the new dynamoDB instance we have to store our data. several of the collections have already been migrated, but some others are taking time. This migration has not been lossless either, some data can't be moved.
It will likely be changed / remigrated so this PR will be up for a little while.

2019-03-26 18:32 UTC, arynh requested changes

2019-03-26 18:32 UTC, arynh commented on src/utils/dataset_db/dynamo_db.py
> +        item_count: number of items uploaded successfully
Would be possible or useful to return the metadata that we get from `table.put_item()`?

2019-03-26 18:32 UTC, arynh commented on src/utils/dataset_db/dynamo_db.py
> +        except Exception as e:
`except Exception as e` hmmm is there a better way

2019-03-26 18:32 UTC, arynh commented on src/utils/dataset_db/dynamo_db.py
> +tables_by_name = {}
What are these global variables for?

2019-03-26 18:32 UTC, arynh commented on src/utils/dataset_db/dynamo_db.py
> +tables_by_name = {}
If they are global, we might want to make them all caps

2019-03-26 18:33 UTC, arynh approved these changes

2019-03-27 05:07 UTC, JoshBurke commented on src/utils/dataset_db/dynamo_db.py
> +        except Exception as e:
no!

2019-03-27 05:09 UTC, JoshBurke commented on src/utils/dataset_db/dynamo_db.py
> +tables_by_name = {}
done

2019-03-27 05:18 UTC, merged